# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://zsh2517.github.io
date_format: "ordinal"
title: zsh2517
subtitle: "qwq"
description: "qwq"
keywords: zhshh, zsh2517, zsh, OI
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zsh2517
# organization: zkh360.com
# organization_url: http://www.zkh360.com
github_username: zsh2517
location: Hebei, China
email: 865564024@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 索引

  -
    href: /archives/
    label: 归档

  -
    href: /wiki/
    label: 百科

  -
    href: /project/
    label: 项目

#   -
#     href: /qwq/
#     label: 测试

  -
    href: /links/
    label: 朋友

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 6
paginate_path: "home/page:num"
excerpt_separator:  '<!-- more -->'
# {{ post.excerpt }}
# 然后，在index.html中：

# {{ post.excerpt }}
# 一般情况下，摘要需要去掉html标签，所以一般这样用：

# {{ post.excerpt | strip_html }}
# 然后，和前一种方法一样，在摘要后面加<!-- more --> 即可。

# https://www.cnblogs.com/coderzh/p/jekyll-readmore.html
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

    project:
        output: true
        permalink: /project/:path/

    # qwq:
    #     output: false
    #     permalink: /qwq/:path/

repository: zsh2517/newblog

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zsh2517
    repo: blog_comments
    oauth:
        client_id: a9beecbd7aef5e3ef135
        client_secret: 0287d5c6122c1783ca2ac89fc56acbaab28e4a64
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zsh2517
    repo: blog_comments
    clientID: a9beecbd7aef5e3ef135
    clientSecret: 0287d5c6122c1783ca2ac89fc56acbaab28e4a64
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
