# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://blog.zsh2517.xyz
date_format: "ordinal"
title: zsh2517
subtitle: ""
description: "qwq"
keywords: zhshh, zsh2517, zsh, OI
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zsh2517
# organization: zkh360.com
# organization_url: http://www.zkh360.com
github_username: zsh2517
location: Hebei, China
email: 865564024@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Index

  -
    href: /categories/
    label: Categories

  -
    href: /archives/
    label: Archives

  -
    href: /wiki/
    label: Wiki

  -
    href: /down/
    label: Download

  -
    href: /qwq/
    label: Test

  -
    href: /links/
    label: Friends

  -
    href: /about/
    label: About

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

    down:
        output: true
        permalink: /down/:path/

    qwq:
        output: true
        permalink: /qwq/:path/

repository: zsh2517/newblog

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zsh2517
    repo: blog_comments
    oauth:
        client_id: a9beecbd7aef5e3ef135
        client_secret: 0287d5c6122c1783ca2ac89fc56acbaab28e4a64
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zsh2517
    repo: blog_comments
    clientID: a9beecbd7aef5e3ef135
    clientSecret: 0287d5c6122c1783ca2ac89fc56acbaab28e4a64
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: true
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
# google:
#     analytics_id: UA-80669434-1
